SomeProducts/Controllers/AdminController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using SomeProducts.Attribute;
using SomeProducts.CrossCutting.Filter.Model;
using SomeProducts.CrossCutting.Helpers;
using SomeProducts.CrossCutting.ProjectLogger;
using SomeProducts.PresentationServices.IPresentationSevices.Admin;
using SomeProducts.PresentationServices.Models;
using SomeProducts.PresentationServices.Models.Admin;
using FilterInfo = SomeProducts.CrossCutting.Filter.Model.FilterInfo;

namespace SomeProducts.Controllers
{
    [AuthorizeRole(UserRole.Admin, UserRole.SuperAdmin)]
    public class AdminController : Controller
    {
        private readonly IUserTablePresentationService _service;
        private readonly ICompanyPresentationService _companyService;

        public AdminController(
            IUserTablePresentationService service,
            ICompanyPresentationService companyService)
        {
            _service = service;
            _companyService = companyService;
        }

        [HttpGet]
        public ActionResult Users(
            int? page,
            int? count,
            string by,
            [ModelBinder(typeof(FilterInfoModelBinder))]FilterInfo filter)
        {
            ProjectLogger.Trace($"User {HttpContext.User.Identity.Name} open admin page");
            var pageInfo = new PageInfo(page, count, by);
            return User.IsInRole(UserRole.SuperAdmin.AsString())
                ? View("SuperAdminUsers", _service.GetSuperAdminUserTableViewModel(pageInfo, filter))
                : View(_service.GetAdminUserTableViewModel(pageInfo, filter));
        }

        [HttpPost]
        public async Task<JsonResult> ChangeUserAdminRole(int userId)
        {
            ProjectLogger.Trace($"User {HttpContext.User.Identity.Name} try change role for user(id={userId})");
            if (!IsActiveUser(userId) || await IsHasRigth(userId))
            {
                await _service.ChangeAdminRole(userId);
            }
            return Json(await _service.GetUserRoles(userId));
        }

        [HttpPost]
        public async Task<JsonResult> SetUserCompany(int userId, int companyId)
        {
            if (!IsActiveUser(userId) || await IsHasRigth(userId))
            {
                await _service.SetUserCompany(userId, companyId);
            }
            return Json(await _service.GetUserCompany(userId));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeRole(UserRole.SuperAdmin)]
        public async Task<ActionResult> RemoveUser(int userId, string redirectUrl)
        {
            ProjectLogger.Trace($"User {HttpContext.User.Identity.Name} try remove user(id={userId})");
            if (!IsActiveUser(userId))
            {
                await _service.RemoveUser(userId);
            }
            return Redirect(redirectUrl);
        }

        [HttpPost]
        public JsonResult GetUserRoles(int userId)
        {
            var roles = _service.GetUserRoles(userId);
            return Json(roles);
        }

        private bool IsActiveUser(int userId)
        {
            var userName = HttpContext.User.Identity.Name;
            return _service.IsUserExist(userId, userName);
        }

        private async Task<bool> IsHasRigth(int userId)
        {
            var userCompany = await _service.GetUserCompany(userId);
            return userCompany.CompanyId == CrossCutting.Constants.Constants.EmtyCompanyId
                   || userCompany.CompanyId == User.GetCompany()
                   || User.IsInRole(UserRole.SuperAdmin.AsString());
        }

        [HttpGet]
        [AuthorizeRole(UserRole.SuperAdmin)]
        public ActionResult Companies()
        {
            var model = _companyService.GetCompaniesViewModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeRole(UserRole.SuperAdmin)]
        public ActionResult RemoveCompany(int companyId)
        {
            if (CrossCutting.Constants.Constants.EmtyCompanyId != companyId)
            {
                _companyService.RemoveCompany(companyId);
            }
            return RedirectToAction("Companies");
        }

        [HttpPost]
        [AuthorizeRole(UserRole.SuperAdmin)]
        public JsonResult UpdateCompany(CompanyModel model)
        {
            _companyService.UpdateCompany(model);
            return Json(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeRole(UserRole.SuperAdmin)]
        public ActionResult CreateCompany(string companyName)
        {
            _companyService.CreteNewCompany(companyName);
            return RedirectToAction("Companies");
        }
    }
}

SomeProducts/Controllers/AuditController.cs
using System.Web.Mvc;
using SomeProducts.Attribute;
using SomeProducts.CrossCutting.Filter.Model;
using SomeProducts.PresentationServices.IPresentationSevices.Audit;
using SomeProducts.PresentationServices.Models;
using FilterInfo = SomeProducts.CrossCutting.Filter.Model.FilterInfo;

namespace SomeProducts.Controllers
{
    [AuthorizeRole(UserRole.Admin, UserRole.SuperAdmin)]
    public class AuditController : Controller
    {
        private readonly IAuditPresentationService _service;

        public AuditController(IAuditPresentationService service)
        {
            _service = service;
        }

        public ActionResult FullAudit(
            int? page,
            int? count,
            string by,
            [ModelBinder(typeof(FilterInfoModelBinder))]FilterInfo filter)
        {
            var pageInfo = new PageInfo(page, count, by);
            var model = _service.GetFullAuditViewTable(pageInfo, filter);
            return View("AuditTable", model);
        }

        public ActionResult ItemAudit(
            int id,
            string entity,
            int? page,
            int? count,
            string by)
        {
            var pageInfo = new PageInfo(page, count, by);
            var model = _service.GetAuditViewTableForItem(pageInfo, entity, id);
            return View("AuditTableForItem", model);
        }
    }
}

SomeProducts/Views/Shared/_Layout.cshtml
@using SomeProducts.Helpers
@using R = Resources.LocalResource
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="author" content="E.Mazurkevich">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @RenderSection("stylesheets", required: false)
</head>
<body>
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="brand" href="@Url.Action("Show", "ProductTable")"><span>SomeProducts</span></a>
                <a class="btn btn-navbar collapsed" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="nav-no-collapse header-nav">
                    <ul class="nav pull-right">
                        <li class="dropdown">
                            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="halflings-icon white globe"></i>
                                @R.Language
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("English", "ChangeCulture", "Account", new {culture = "en", returnUrl = Request.RawUrl}, null)</li>
                                <li>@Html.ActionLink("Русский", "ChangeCulture", "Account", new {culture = "ru", returnUrl = Request.RawUrl}, null)</li>
                            </ul>
                        </li>
                        @Html.Partial("_LoginPartial")
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid-full">
        <div class="row-fluid">
            <div id="sidebar-left" class="span2">
                <div class="nav-collapse sidebar-nav collapse">
                    <ul class="nav nav-tabs nav-stacked main-menu">
                        <li><a href="@Url.Action("Show", "ProductTable")"><i class="icon-shopping-cart"></i><span class="hidden-tablet">@R.Products</span></a></li>
                        @if (User.IsInUserRole(UserRole.Admin) || User.IsInUserRole(UserRole.SuperAdmin))
                        {
                            <li><a href="@Url.Action("Create", "Product")"><i class="icon-plus"></i><span class="hidden-tablet">@R.NewProduct</span></a></li>
                            <li><a href="@Url.Action("FullAudit", "Audit")"><i class="icon-bar-chart"></i><span class="hidden-tablet">@R.FullAudit</span></a></li>
                            <li><a href="@Url.Action("Users", "Admin")"><i class="icon-user"></i><span class="hidden-tablet">@R.Users</span></a></li>
                        }
                        @if (User.IsInUserRole(UserRole.SuperAdmin))
                        {
                            <li><a href="@Url.Action("Companies", "Admin")"><i class="icon-briefcase"></i><span class="hidden-tablet">@R.Companies</span></a></li>
                        }
                    </ul>
                </div>
            </div>
            <div id="content" class="span10">
                @RenderBody()
            </div>
        </div>
    </div>
<footer>
    <p><p>&copy; @DateTime.Now.Year - My ASP.NET Application</p></p>
</footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/janux")
    @RenderSection("scripts", required: false)
    
</body>
</html>